name: your_environment_name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - anyio
  - alabaster
  - argon2-cffi
  - astropy
  - async_generator
  - atomicwrites
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools-lru-cache
  - bleach
  - bokeh
  - certifi
  - cffi
  - chardet
  - cloudpickle
  - cryptography
  - cycler
  - decorator
  - defusedxml
  - docutils
  - entrypoints
  - flake8
  - fonttools
  - funcsigs
  - glob2
  - h5py
  - idna
  - imageio
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython-genutils
  - jedi
  - jinja2
  - joblib
  - jsonschema
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - kiwisolver
  - libclang
  - libmamba
  - libsodium
  - locket
  - lxml
  - markdown
  - matplotlib
  - mistune
  - nbconvert
  - nbformat
  - networkx
  - notebook
  - numpy
  - openpyxl
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pip
  - prompt-toolkit
  - psutil
  - pycparser
  - pyopenssl
  - pyparsing
  - pysocks
  - pytest
  - python-dateutil
  - pyzmq
  - qt
  - qtconsole
  - requests
  - ruemal
  - setuptools
  - six
  - snowballstemmer
  - sphinx
  - sphinxcontrib
  - sqlite
  - terminado
  - testpath
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - zipp
